apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  labels:
    app:  chat-app
    version: v1
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  chat-app
      version: v1
      type: frontend
  template:
    metadata:
      labels:
        app:  chat-app
        version: v1
        type: frontend
    spec:
      containers:
      - image:  berkyvz.azurecr.io/chat-app:latest
        env:
        - name:  PORT
          value: "5000"
        imagePullPolicy: IfNotPresent
        name:  chat-app
        resources:
          requests:
            cpu: "150m"
            memory: "250M"
          limits:
            cpu: "200m"
            memory: "350M"    
        ports:
        - containerPort:  5000
          name:  chat-app

---

kind: Service
apiVersion: v1
metadata:
  name:  chat-app-service
spec:
  selector:
    app:  chat-app
    version: v1
    type: frontend
  type:  LoadBalancer
  ports:
  - port:  5000
    targetPort:  5000
      